/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.7 */
/* Wed Jan 29 17:02:16 2020 */

/* parameterized module instance */
OscPll __ (.CLKI( ), .CLKOP( ));
