/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.7 */
/* Fri Jan 24 15:05:00 2020 */

/* parameterized module instance */
plltest __ (.CLKI( ), .CLKOP( ));
