/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.2.446 */
/* Module Version: 5.4 */
/* Thu Feb 06 17:29:44 2020 */

/* parameterized module instance */
Sin_qlut __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
