/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.4 */
/* Mon Jan 27 10:53:18 2020 */

/* parameterized module instance */
SineLUT __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
